name: Environment Test

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  envtesr:
    name: Environment Test
    runs-on: ubuntu-latest
    environment: main
    steps:
    - name: Checkout code
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
    - run: echo $TEST_VAR end
    - run: echo $TEST_SECRET end
      