name: Environment Test

on:
  pull_request: {}
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  envtesr:
    name: Environment Test
    runs-on: ubuntu-latest
    environment: main
    steps:
    - name: Checkout code
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
    - name: Configure AWS Access
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubAction-Wildsea
        role-session-name: GitHubTest
    - name: GetCallerIdentity
      run: aws sts get-caller-identity
