name: Environment Test

on:
  pull_request: {}
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  envtesr:
    name: Environment Test
    runs-on: ubuntu-latest
    environment: main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
    - name: Configure AWS Access
      uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubAction-Wildsea
        role-session-name: GitHubTest
        aws-region: ${{ secrets.AWS_REGION }}
    - name: terraform plan
      uses: dflook/terraform-plan@d9df4f6c2484e709ba7ffaa16c98a6906f4760cd
      with:
        path: terraform/environment/github
        variables: |
          aws_account="${{ secrets.AWS_ACCOUNT }}"
          aws_region=${{ secrets.AWS_REGION }}
